language: c
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
      - libc6-dev

compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=master
before_install:
  - sudo apt-get -qq update
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
branches:
  only:
    - master

script:
  - rake test
